site_name: OSCP Quick Reference
site_description: PakCyberbot's OSCP Notes and Environment
site_url: https://pakcyberbot.com/OSCP-Notes-and-Environment

repo_url: https://github.com/pakcyberbot/OSCP-Notes-and-Environment

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preferences

  features:
    - content.code.copy
    - content.code.select
    - content.action.view
    - content.tooltips
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.expand   
    - search.share
    - search.suggest

markdown_extensions:
  - tables
  - attr_list
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search